homeassistant:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_timezone
  name: Settings
  auth_providers:
    - type: homeassistant
    # - type: trusted_networks
    #   trusted_networks:
    #     - 172.19.0.0/16
    #     - 10.0.12.0/24

http:

frontend:

view_event:

input_number: !include_dir_named input_numbers
input_boolean: !include_dir_named input_booleans
