homeassistant:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_timezone
  name: Settings

http:
  server_port: !secret settings_server_port

frontend:

input_number: !include_dir_named input_numbers
