homeassistant:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_timezone
  name: Settings
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 172.19.0.0/16
        - 10.0.12.0/24
        - 10.0.11.174/32
      allow_bypass_login: true
    - type: homeassistant

view_event:
  name: settings
  components: []

http:
  base_url: https://automation.prettybaked.com
  server_port: !secret settings_server_public_port
  
frontend:

config:

input_number: !include_dir_named input_numbers
input_boolean: !include_dir_named input_booleans
